PLAT-4831 Unit tests for helpdesk dynamic rendering app
symphonyoss/GroupID pull request #109
Opened 2018-03-26 13:25 UTC by lumoura

This PR aims to give full unit test coverage to the front-end app module of the Helpdesk bot system.

2018-03-26 18:28 UTC, robson-sanchez requested changes

2018-03-26 18:28 UTC, robson-sanchez commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionAttachmentEnricherTest.js
> +global.SYMPHONY = {
I believe this object might be:

```
global.SYMPHONY = {
  services: {
    subscribe: subscribe
  }
}
```

Please review other tests to address this comment.

2018-03-26 18:28 UTC, robson-sanchez commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionAttachmentEnricherTest.js
> +        expect(typeof actionFactory.mock.calls[0][1] === 'string').toBe(true);
It would be better validate the param value instead of param type.

This comment can be applied to other tests.

2018-03-26 18:28 UTC, robson-sanchez commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionAttachmentEnricherTest.js
> +        expect(entityRegistry.updateEnricher.mock.calls[0][1]).toBe(undefined);
Why are those arguments undefined? Probably you should mock 'actionFactory' and 'actions' functions.

This comment can be applied to other tests.

2018-03-26 18:28 UTC, rsanchez-daitan commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionClaimTicketEnricherTest.js
> +            expect(base64.escape.mock.calls.length).toBe(mockInRoomList.length);
expect(base64.escape.mock.calls.length).toBe(1);

2018-03-26 18:28 UTC, rsanchez-daitan commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionClaimTicketEnricherTest.js
> +            for(const room of mockInRoomList) {
You don't need this for statement once you have one value.

2018-03-26 18:28 UTC, rsanchez-daitan commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionClaimTicketEnricherTest.js
> +            expect(entityRegistry.updateEnricher.mock.calls[0][1]).toBe(undefined);
Undefined?

2018-03-26 18:28 UTC, rsanchez-daitan commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionClaimTicketEnricherTest.js
> +            expect(typeof actionFactory.mock.calls[0][1]).toEqual('string');
Please validate the value instead of type.

2018-03-27 11:35 UTC, lumoura commented on helpdesk-dynamic-rendering/src/main/webapp/enrichers/__tests__/actionAttachmentEnricherTest.js
> +global.SYMPHONY = {
done!

2018-03-27 18:22 UTC, robson-sanchez approved these changes

2018-03-27 18:23 UTC, merged